return PlaceObj('ModDef', {
	'title', "Unreal Mars",
	'description', "<br>A set of differents things inspired by the Unreal universe.\n<br>\n<br>For now :\n<br> - 7 Logo\n<br> - 1 Mission Sponsor\n<br> - 8 Commander Profile \n<br> - 2 Radios\n<br>\n<br>More to come ...\n\nThe mod files, for any comments and suggestions : \nhttps://github.com/Fx73/Unreal-Mars",
	'image', "ModInfos/skaarj.jpg",
	'last_changes', "Upgrading Game version",
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		".gitignore",
		"README.md",
	},
	'id', "hlgeCBW",
	'steam_id', "2596819682",
	'pops_desktop_uuid', "a73fee5a-d983-4902-a27b-d23a4ab74dc9",
	'pops_any_uuid', "39c03244-60d5-4b65-8ea5-fb0cb33fedea",
	'author', "unknown",
	'version_major', 1,
	'version_minor', 3,
	'version', 88,
	'lua_revision', 1007000,
	'saved_with_revision', 1007783,
	'saved', 1631129269,
	'screenshot1', "ModInfos/capture.png",
	'TagCommanderProfiles', true,
	'TagMissionSponsors', true,
	'TagColonyLogos', true,
	'TagRadio', true,
})