return PlaceObj('ModDef', {
	'title', "Unreal",
	'description', "<br>A set of differents things inspired by the Unreal universe.\n<br>\n<br>For now :\n<br> - 7 Logo\n<br> - 1 Mission Sponsor\n<br> - 8 Commander Profile \n<br> - 2 Radios\n<br>\n<br>More to come ...",
	'image', "Images/skaarj.jpg",
	'last_changes', "Added 8 Commander",
	'id', "hlgeCBW",
	'pops_desktop_uuid', "a73fee5a-d983-4902-a27b-d23a4ab74dc9",
	'pops_any_uuid', "39c03244-60d5-4b65-8ea5-fb0cb33fedea",
	'author', "unknown",
	'version_major', 1,
	'version_minor', 2,
	'version', 70,
	'lua_revision', 233360,
	'saved_with_revision', 252384,
	'saved', 1592615745,
	'TagCommanderProfiles', true,
	'TagMissionSponsors', true,
	'TagColonyLogos', true,
	'TagRadio', true,
})